name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [master]

env:
  AWS_REGION: ap-northeast-1
  APPLICATION_NAME: railway-timer
  ENVIRONMENT_NAME: Railway-timer-env-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v4

      - name: Create deployment package
        run: |
          zip -r app.zip * -x ".*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 # v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/aws-elasticbeanstalk-deploy@v1.0.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          application-name: ${{ env.APPLICATION_NAME }}
          environment-name: ${{ env.ENVIRONMENT_NAME }}
          version-label: nodejs-${{ github.sha }}
          deployment-package-path: app.zip
          option-settings: |
            [
              {
                "Namespace": "aws:autoscaling:launchconfiguration",
                "OptionName": "IamInstanceProfile",
                "Value": "aws-elasticbeanstalk-ec2-role"
              },
              {
                "Namespace": "aws:elasticbeanstalk:environment",
                "OptionName": "ServiceRole",
                "Value": "aws-elasticbeanstalk-service-role"
              },
              {
                "Namespace": "aws:elasticbeanstalk:application:environment",
                "OptionName": "ODPT_CONSUMER_KEY",
                "Value": "${{ secrets.ODPT_CONSUMER_KEY }}"
              }
            ]